namespace: finallycoffee
name: fediverse
version: 0.1.2
readme: README.md
authors:
- transcaffeine <transcaffeine@finally.coffee>
description: Deploying fediverse software, mostly ActivityPub based
dependencies:
  "community.docker": "^4.0.0"
  "community.general": "^10.6.0"
license_file: LICENSE.md
build_ignore:
- '*.tar.gz'
repository: https://git.finally.coffee/finallycoffee/fediverse
issues: https://codeberg.org/finallycoffee/ansible-collection-fediverse/issues
tags:
  - activitypub
  - fediverse
  - fediwall
  - sharkey
  - gotosocial
  - mastodon
