namespace: finallycoffee
name: fediverse
version: 0.0.1
readme: README.md
authors:
- Johanna Dorothea Reichmann <transcaffeine@finallycoffee.eu>
description: Various ansible roles for deploying fediverse software
dependencies:
  "community.docker": "^1.10.0"
license:
- CNPLv7+
build_ignore:
- '*.tar.gz'
repository: https://git.finallycoffee.eu/finallycoffee.eu/fediverse
issues: https://git.finallycoffee.eu/finallycoffee.eu/fediverse/issues
