namespace: finallycoffee
name: fediverse
version: 0.0.1
readme: README.md
authors:
- transcaffeine <transcaffeine@finally.coffee>
description: Deploying fediverse software, mostly ActivityPub based
dependencies:
  "community.docker": "^1.10.0"
license_file: LICENSE.md
build_ignore:
- '*.tar.gz'
repository: https://git.finally.coffee/finallycoffee/fediverse
issues: https://git.finally.coffee/finallycoffee/fediverse/issues
