---
- name: Ensure container image '{{ fediwall_container_image }}' is {{ fediwall_state }}
  community.docker.docker_image:
    name: "{{ fediwall_container_image }}"
    state: "{{ fediwall_state }}"
    source: "{{ fediwall_container_image_source }}"
    force_source: "{{ fediwall_container_image_force_source }}"

- name: Ensure container '{{ fediwall_container_name }}' is {{ fediwall_container_state }}
  community.docker.docker_container:
    name: "{{ fediwall_container_name }}"
    image: "{{ fediwall_container_image }}"
    env: "{{ fediwall_container_env | default(omit, true) }}"
    user: "{{ fediwall_container_user | default(omit, true) }}"
    ports: "{{ fediwall_container_ports | default(omit, true) }}"
    state: "{{ fediwall_container_state }}"
